### ISSUE TITLE
java.lang.InternalError: Malformed class name

### ISSUE THREAD

**Issue by pancodia** [beloglazov/couchdb-scala#13]
I followed README and experimented in Scala 2.11.0 REPL. But When I ran:

``` scala
val typeMapping = TypeMapping(classOf[Person] -> "Person")
```

I encountered the following error:

```
scala> val typeMapping = TypeMapping(classOf[Person] -> "Person")
java.lang.InternalError: Malformed class name
  at java.lang.Class.getSimpleName(Class.java:1322)
  at java.lang.Class.getCanonicalName(Class.java:1391)
  at com.ibm.couchdb.TypeMapping$$anonfun$apply$1.apply(TypeMapping.scala:27)
  at com.ibm.couchdb.TypeMapping$$anonfun$apply$1.apply(TypeMapping.scala:27)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at com.ibm.couchdb.TypeMapping$.apply(TypeMapping.scala:27)
  ... 35 elided
```

What is the problem?

**Update**

When I ran the last example using sbt, the program was executed successfully. Anyone can point me to the right direction to understand this issue?

**Comment by ermyas** [comment]
I think this is a bug in the Scala REPL. See
- https://issues.scala-lang.org/browse/SI-9051
- https://issues.scala-lang.org/browse/SI-2034

**Comment by pancodia** [comment]
This problem can be avoided by compiling the Person class first and then import in the Scala REPL.

**Comment by rushabh780** [comment]
Thanks @pancodia .. 
It worked :)
