### ISSUE TITLE
Cannot run a basic helloworld on Windows

### ISSUE THREAD

**Issue by mpierre0220** [beloglazov/couchdb-scala#68]
I have installed Scala and Couchdb on Windows. I have cloned the couchdb-scala repository. I get to following error when I run a basic file.

C:\cdbs\couchdb-scala>sbt "run-main com.ibm.couchdb.examples.Basic"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading project definition from C:\cdbs\couchdb-scala\project
[info] Updating {file:/C:/cdbs/couchdb-scala/project/}couchdb-scala-build...
[info] Resolving com.typesafe.sbt#sbt-native-packager;1.1.0-RC1 ...
[warn]  module not found: com.typesafe.sbt#sbt-native-packager;1.1.0-RC1
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.11/sbt_1.0.0-M4//1.1.0-RC1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.11/sbt_1.0.0-M4//1.1.0-RC1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\IBM_ADMIN\.ivy2\local\com.typesafe.sbt\sbt-native-packager\scala_2.11\sbt_1.0.0-M4\\1.1.0-RC1\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.11_1.0.0-M4/1.1.0-RC1/sbt-native-packager-1.1.0-RC1.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/typesafe/sbt/sbt-native-packager_2.11_1.0.0-M4/1.1.0-RC1/sbt-native-packager-1.1.0-RC1.pom
[info] Resolving com.eed3si9n#sbt-assembly;0.14.2 ...
[warn]  module not found: com.eed3si9n#sbt-assembly;0.14.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-assembly/scala_2.11/sbt_1.0.0-M4//0.14.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.11/sbt_1.0.0-M4//0.14.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\IBM_ADMIN\.ivy2\local\com.eed3si9n\sbt-assembly\scala_2.11\sbt_1.0.0-M4\\0.14.2\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.11_1.0.0-M4/0.14.2/sbt-assembly-0.14.2.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/eed3si9n/sbt-assembly_2.11_1.0.0-M4/0.14.2/sbt-assembly-0.14.2.pom
[info] Resolving org.brianmckenna#sbt-wartremover;0.14 ...
[warn]  module not found: org.brianmckenna#sbt-wartremover;0.14
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.brianmckenna/sbt-wartremover/scala_2.11/sbt_1.0.0-M4//0.14/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.brianmckenna/sbt-wartremover/scala_2.11/sbt_1.0.0-M4//0.14/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\IBM_ADMIN\.ivy2\local\org.brianmckenna\sbt-wartremover\scala_2.11\sbt_1.0.0-M4\\0.14\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/brianmckenna/sbt-wartremover_2.11_1.0.0-M4/0.14/sbt-wartremover-0.14.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/org/brianmckenna/sbt-wartremover_2.11_1.0.0-M4/0.14/sbt-wartremover-0.14.pom
[info] Resolving org.scalastyle#scalastyle-sbt-plugin;0.8.0 ...
[warn]  module not found: org.scalastyle#scalastyle-sbt-plugin;0.8.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scalastyle/scalastyle-sbt-plugin/scala_2.11/sbt_1.0.0-M4//0.8.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scalastyle/scalastyle-sbt-plugin/scala_2.11/sbt_1.0.0-M4//0.8.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\IBM_ADMIN\.ivy2\local\org.scalastyle\scalastyle-sbt-plugin\scala_2.11\sbt_1.0.0-M4\\0.8.0\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalastyle/scalastyle-sbt-plugin_2.11_1.0.0-M4/0.8.0/scalastyle-sbt-plugin-0.8.0.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/org/scalastyle/scalastyle-sbt-plugin_2.11_1.0.0-M4/0.8.0/scalastyle-sbt-plugin-0.8.0.pom
[info] Resolving com.jsuereth#sbt-pgp;1.0.0 ...
[warn]  module not found: com.jsuereth#sbt-pgp;1.0.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.jsuereth/sbt-pgp/scala_2.11/sbt_1.0.0-M4//1.0.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.11/sbt_1.0.0-M4//1.0.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\IBM_ADMIN\.ivy2\local\com.jsuereth\sbt-pgp\scala_2.11\sbt_1.0.0-M4\\1.0.0\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/jsuereth/sbt-pgp_2.11_1.0.0-M4/1.0.0/sbt-pgp-1.0.0.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/jsuereth/sbt-pgp_2.11_1.0.0-M4/1.0.0/sbt-pgp-1.0.0.pom
[info] Resolving org.xerial.sbt#sbt-sonatype;0.2.1 ...
[warn]  module not found: org.xerial.sbt#sbt-sonatype;0.2.1
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.xerial.sbt/sbt-sonatype/scala_2.11/sbt_1.0.0-M4//0.2.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.xerial.sbt/sbt-sonatype/scala_2.11/sbt_1.0.0-M4//0.2.1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\IBM_ADMIN\.ivy2\local\org.xerial.sbt\sbt-sonatype\scala_2.11\sbt_1.0.0-M4\\0.2.1\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/xerial/sbt/sbt-sonatype_2.11_1.0.0-M4/0.2.1/sbt-sonatype-0.2.1.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/org/xerial/sbt/sbt-sonatype_2.11_1.0.0-M4/0.2.1/sbt-sonatype-0.2.1.pom
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbt#sbt-native-packager;1.1.0-RC1: not found
[warn]  :: com.eed3si9n#sbt-assembly;0.14.2: not found
[warn]  :: org.brianmckenna#sbt-wartremover;0.14: not found
[warn]  :: org.scalastyle#scalastyle-sbt-plugin;0.8.0: not found
[warn]  :: com.jsuereth#sbt-pgp;1.0.0: not found
[warn]  :: org.xerial.sbt#sbt-sonatype;0.2.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          org.xerial.sbt:sbt-sonatype:0.2.1 (scalaVersion=2.11, sbtVersion=1.0.0-M4)
[warn]          com.jsuereth:sbt-pgp:1.0.0 (scalaVersion=2.11, sbtVersion=1.0.0-M4)
[warn]          com.eed3si9n:sbt-assembly:0.14.2 (scalaVersion=2.11, sbtVersion=1.0.0-M4)
[warn]          org.brianmckenna:sbt-wartremover:0.14 (scalaVersion=2.11, sbtVersion=1.0.0-M4)
[warn]          org.scalastyle:scalastyle-sbt-plugin:0.8.0 (scalaVersion=2.11, sbtVersion=1.0.0-M4)
[warn]          com.typesafe.sbt:sbt-native-packager:1.1.0-RC1 (scalaVersion=2.11, sbtVersion=1.0.0-M4)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          org.xerial.sbt:sbt-sonatype:0.2.1 (scalaVersion=2.11, sbtVersion=1.0.0-M4) (C:\cdbs\couchdb-scala\project\plugins.sbt#L13-14)
[warn]            +- default:couchdb-scala-build:0.1-SNAPSHOT (scalaVersion=2.11, sbtVersion=1.0.0-M4)
[warn]          com.jsuereth:sbt-pgp:1.0.0 (scalaVersion=2.11, sbtVersion=1.0.0-M4) (C:\cdbs\couchdb-scala\project\plugins.sbt#L11-12)
[warn]            +- default:couchdb-scala-build:0.1-SNAPSHOT (scalaVersion=2.11, sbtVersion=1.0.0-M4)
[warn]          com.eed3si9n:sbt-assembly:0.14.2 (scalaVersion=2.11, sbtVersion=1.0.0-M4) (C:\cdbs\couchdb-scala\project\plugins.sbt#L5-6)
[warn]            +- default:couchdb-scala-build:0.1-SNAPSHOT (scalaVersion=2.11, sbtVersion=1.0.0-M4)
[warn]          org.brianmckenna:sbt-wartremover:0.14 (scalaVersion=2.11, sbtVersion=1.0.0-M4) (C:\cdbs\couchdb-scala\project\plugins.sbt#L7-8)
[warn]            +- default:couchdb-scala-build:0.1-SNAPSHOT (scalaVersion=2.11, sbtVersion=1.0.0-M4)
[warn]          org.scalastyle:scalastyle-sbt-plugin:0.8.0 (scalaVersion=2.11, sbtVersion=1.0.0-M4) (C:\cdbs\couchdb-scala\project\plugins.sbt#L9-10)
[warn]            +- default:couchdb-scala-build:0.1-SNAPSHOT (scalaVersion=2.11, sbtVersion=1.0.0-M4)
[warn]          com.typesafe.sbt:sbt-native-packager:1.1.0-RC1 (scalaVersion=2.11, sbtVersion=1.0.0-M4) (C:\cdbs\couchdb-scala\project\plugins.sbt#L3-4)
[warn]            +- default:couchdb-scala-build:0.1-SNAPSHOT (scalaVersion=2.11, sbtVersion=1.0.0-M4)
sbt.internal.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-native-packager;1.1.0-RC1: not found
unresolved dependency: com.eed3si9n#sbt-assembly;0.14.2: not found
unresolved dependency: org.brianmckenna#sbt-wartremover;0.14: not found
unresolved dependency: org.scalastyle#scalastyle-sbt-plugin;0.8.0: not found
unresolved dependency: com.jsuereth#sbt-pgp;1.0.0: not found
unresolved dependency: org.xerial.sbt#sbt-sonatype;0.2.1: not found
        at sbt.internal.librarymanagement.IvyActions$.sbt$internal$librarymanagement$IvyActions$$resolve(IvyActions.scala:370)
        at sbt.internal.librarymanagement.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:203)
        at sbt.internal.librarymanagement.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:179)
        at sbt.internal.librarymanagement.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:158)
        at sbt.internal.librarymanagement.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:158)
        at sbt.internal.librarymanagement.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:134)
        at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:59)
        at sbt.internal.librarymanagement.IvySbt$$anon$4.call(Ivy.scala:67)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:67)
        at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:129)
        at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:126)
        at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:158)
        at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:179)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1494)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1490)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$94.apply(Defaults.scala:1525)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$94.apply(Defaults.scala:1523)
        at sbt.internal.util.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:40)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1528)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1522)
        at sbt.internal.util.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:63)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1545)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1472)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1424)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:44)
        at sbt.internal.util.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:229)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:229)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:238)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:229)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:229)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:161)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.internal.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-native-packager;1.1.0-RC1: not found
[error] unresolved dependency: com.eed3si9n#sbt-assembly;0.14.2: not found
[error] unresolved dependency: org.brianmckenna#sbt-wartremover;0.14: not found
[error] unresolved dependency: org.scalastyle#scalastyle-sbt-plugin;0.8.0: not found
[error] unresolved dependency: com.jsuereth#sbt-pgp;1.0.0: not found
[error] unresolved dependency: org.xerial.sbt#sbt-sonatype;0.2.1: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by ermyas** [comment]
hi @mpierre0220, this issue is caused by the sbt version you are using. Please use the current stable version (0.13) and not the beta version 1.0
